from django.db import models


class Planning(models.Model):
    id = models.IntegerField(primary_key=True)
    application_number = models.CharField(max_length=45, unique=True)
    development_address = models.TextField()
    development_description = models.TextField()
    decision_type = models.TextField()
    registered_date = models.DateTimeField(null=True)
    registered_in_last_7_working_days = models.TextField()
    registered_in_last_28_working_days = models.TextField()
    earliest_decision_date = models.DateTimeField(null=True)
    decision_date = models.DateTimeField(null=True)
    decision_level = models.TextField()
    system_status = models.TextField()
    system_status_change_date = models.DateTimeField(null=True)
    applicant_name = models.TextField()
    ward = models.TextField()
    conservation_areas = models.TextField()
    neighbourhood_areas = models.TextField()
    case_officer = models.TextField()
    case_officer_team = models.TextField()
    responsibility_type = models.TextField()
    comment = models.TextField()
    full_application = models.TextField()
    application_type = models.TextField()
    easting = models.IntegerField(default=-1)
    northing = models.IntegerField(default=-1)
    longitude = models.DecimalField(decimal_places=9, max_digits=11, default=-1.00)
    latitude = models.DecimalField(decimal_places=9, max_digits=11, default=-1.00)
    spatial_accuracy = models.TextField()
    last_updated = models.DateTimeField(null=True)
    socrata_id = models.IntegerField(unique=True)
    organisation_uri = models.TextField()
