# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='decision_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='earliest_decision_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='registered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning',
            name='system_status_change_date',
            field=models.DateTimeField(),
        ),
    ]
