# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20170702_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='earliest_decision_date',
            field=models.DateTimeField(null=True),
        ),
    ]
